on:
  release:
    types: published

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    name: Build HTML, push container and deploy HTML
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the image and export HTML
      uses: ./
      with:
        entrypoint: model/entrypoint.sh
        model-name: capella-automations
        path-model-folder: model/capella-automations

    - name: Deploy HTML to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: artifacts

    - name: Push image to Dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mtreber/capella-html-exporter
        tag_with_ref: true