name: Publish Docker image
on:
  release:
    types: [published]
jobs:
#https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mtreber/capella-html-exporter
          tag_with_ref: true
#https://github.com/marketplace/actions/github-pages-action
  deploy:
    runs-on: mtreber/capella-html-exporter
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

