on:
  release:
    types: published

jobs:
  build_publish:
    runs-on: ubuntu-latest
    name: Push container to Dockerhub
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to Dockerhub
      uses: docker/build-push-action@v4
      with:
        tags: mtreber/capella-html-exporter:v6.1.0-0
        push: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test using the action
      uses: ./
      with:
        model-name: capella-automations
        path-model-folder: model/capella-automations
        entrypoint: model/entrypoint.sh

    - name: Archive HTML export and validation report
      uses: actions/upload-artifact@v3
      with:
        name: validation-report-html-export
        path: artifacts